// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// Generated with Bot Builder V4 SDK Template for Visual Studio SkillRootBot v4.7.1

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AdaptiveCards;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Integration.AspNet.Core;
using Microsoft.Bot.Builder.Integration.AspNet.Core.Skills;
using Microsoft.Bot.Builder.Skills;
using Microsoft.Bot.Builder.Teams;
using Microsoft.Bot.Connector.Authentication;
using Microsoft.Bot.Schema;
using Microsoft.Bot.Schema.Teams;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ParentBot.Bots
{
    public class RootBot : TeamsActivityHandler
    {
        private readonly string _botId;
        private readonly ConversationState _conversationState;
        private readonly SkillHttpClient _skillClient;
        private readonly SkillsConfiguration _skillsConfig;

        public RootBot(ConversationState conversationState, SkillsConfiguration skillsConfig, SkillHttpClient skillClient, IConfiguration configuration)
        {
            _conversationState = conversationState ?? throw new ArgumentNullException(nameof(conversationState));
            _skillsConfig = skillsConfig ?? throw new ArgumentNullException(nameof(skillsConfig));
            _skillClient = skillClient ?? throw new ArgumentNullException(nameof(skillsConfig));
            if (configuration == null)
            {
                throw new ArgumentNullException(nameof(configuration));
            }

            _botId = configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppIdKey)?.Value;
            if (string.IsNullOrWhiteSpace(_botId))
            {
                throw new ArgumentException($"{MicrosoftAppCredentials.MicrosoftAppIdKey} is not set in configuration");
            }
        }


        private Attachment GetOptionsAttachment()
        {
            HeroCard heroCard = null;
            if (_skillsConfig.Skills.Count > 0)
            {
                var buttons = new List<CardAction>();

                //  Hard code for testing synchronous operations
               // buttons.Add(new CardAction(ActionTypes.ImBack, title: $"health test invoke", text: "health test invoke", value: "health test invoke"));
                //buttons.Add(new CardAction(ActionTypes.ImBack, title: $"health test expectReplies", text: "health test expectReplies", value: "health test expectReplies"));
                buttons.Add(new CardAction(ActionTypes.ImBack, title: $"invoke", text: "invoke", value: "invoke"));
                buttons.Add(new CardAction(ActionTypes.ImBack, title: $"expectReplies Echo", text: "expectReplies Echo", value: "expectReplies"));
                buttons.Add(new CardAction(ActionTypes.ImBack, title: $"teams adaptive card", text: "teams adaptive card", value: "teams adaptive card"));
                buttons.Add(new CardAction("invoke", "teams invoke", null, null, null, JObject.Parse(@"{ ""key"" : ""value"" }")));
                
                heroCard = new HeroCard
                {
                    Title = "Skills Options",
                    Text = "Click one of the buttons below to initiate that skill.",
                    Buttons = buttons
                };
            }
            else
            {
                heroCard = new HeroCard
                {
                    Title = "No Skills configured...",
                    Subtitle = "Configure some skills in appsettings.json",
                };
            }

            return heroCard.ToAttachment();
        }

        private Attachment GetAdaptiveCardWithInvokeAction()
        {
            var adaptiveCard = new AdaptiveCard();
            adaptiveCard.Body.Add(new AdaptiveTextBlock("Bot Builder Invoke Action"));
            var action4 = new CardAction("invoke", "invoke", null, null, null, JObject.Parse(@"{ ""key"" : ""value"" }"));
            adaptiveCard.Actions.Add(action4.ToAdaptiveCardAction());

            return adaptiveCard.ToAttachment();
        }

        private async Task SendToSkill(ITurnContext turnContext, BotFrameworkSkill targetSkill, Activity activity = null, CancellationToken cancellationToken = default)
        {
            // NOTE: Always SaveChanges() before calling a skill so that any activity generated by the skill
            // will have access to current accurate state.
            await _conversationState.SaveChangesAsync(turnContext, force: true, cancellationToken: cancellationToken);

            var activityToSend = activity ?? (Activity)turnContext.Activity;

            if (activityToSend.Type == ActivityTypes.Invoke)
            {
                var invokeResponse = await PostActivityToSkill<JObject>(targetSkill, activityToSend, cancellationToken);

                if (invokeResponse != null)
                {
                    await turnContext.SendActivityAsync("Received Invoke Response Body: " + invokeResponse.ToString());
                }
            }
            else
            {
                var expectedReplies = await PostActivityToSkill<ExpectedReplies>(targetSkill, activityToSend, cancellationToken);

                if (expectedReplies != null && activity.DeliveryMode == DeliveryModes.ExpectReplies)
                {
                    // sending messages back requires the turnContext.Activity.DeliveryMode to NOT be ExpectReplies, so change it back
                    turnContext.Activity.DeliveryMode = DeliveryModes.Normal;
                    foreach (var a in expectedReplies.Activities)
                    {
                        a.Text = $"ExpectedReplies: {a.Text}";
                        await turnContext.SendActivityAsync(a);
                    }
                }
            }
        }

        private async Task<T> PostActivityToSkill<T>(BotFrameworkSkill targetSkill, Activity activity, CancellationToken cancellationToken)
        {
            // route the activity to the skill
            var response = await _skillClient.PostActivityAsync<T>(_botId, targetSkill, _skillsConfig.SkillHostEndpoint, activity, cancellationToken);

            // Check response status
            if (!(response.Status >= 200 && response.Status <= 299))
            {
                throw new HttpRequestException($"Error invoking the skill id: \"{targetSkill.Id}\" at \"{targetSkill.SkillEndpoint}\" (status is {response.Status}). \r\n {response.Body}");
            }

            return response.Body;
        }

        protected override async Task<InvokeResponse> OnTeamsCardActionInvokeAsync(ITurnContext<IInvokeActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(MessageFactory.Text("hello from OnTeamsCardActionInvokeAsync."));
            await turnContext.SendActivityAsync(MessageFactory.Attachment(GetOptionsAttachment()), cancellationToken);

            return new InvokeResponse() { Status = (int)HttpStatusCode.OK };
        }

        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var text = turnContext.Activity.Text;

            if (!string.IsNullOrEmpty(text))
            {
                if (text.Contains("teams"))
                {
                    var reply = MessageFactory.Attachment(GetAdaptiveCardWithInvokeAction());
                    await turnContext.SendActivityAsync(reply, cancellationToken);
                    return;
                }

                var activity = JsonConvert.DeserializeObject<Activity>(JsonConvert.SerializeObject(turnContext.Activity, HttpHelper.BotMessageSerializerSettings));
                if (text.Contains("invoke"))
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text($"Got it, connecting you to the skill using {text}..."), cancellationToken);
                    // HACK the current message, wich is being fwded to the child bot, 
                    // and force the child bot to respond synchronously by changing the message type to Invoke
                    activity.Type = ActivityTypes.Invoke;
                }
                else if (text.Contains("expectReplies"))
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text($"Got it, connecting you to the skill using {text}..."), cancellationToken);
                    // HACK the current message, wich is being fwded to the child bot, 
                    // and force the child bot to respond synchronously via ExpectReplies
                    activity.DeliveryMode = DeliveryModes.ExpectReplies;
                }

                // Send the activity to the skill
                await SendToSkill(turnContext, _skillsConfig.Skills.Values.First(), activity, cancellationToken);

            }

            // just respond with choices
            await turnContext.SendActivityAsync(MessageFactory.Attachment(GetOptionsAttachment()), cancellationToken);

            // Save conversation state
            await _conversationState.SaveChangesAsync(turnContext, force: true, cancellationToken: cancellationToken);
        }


        protected override async Task OnEndOfConversationActivityAsync(ITurnContext<IEndOfConversationActivity> turnContext, CancellationToken cancellationToken)
        {
            // forget skill invocation
            //await _activeSkillProperty.DeleteAsync(turnContext, cancellationToken);

            // Show status message, text and value returned by the skill
            var eocActivityMessage = $"Received {ActivityTypes.EndOfConversation}.\n\nCode: {turnContext.Activity.Code}";
            if (!string.IsNullOrWhiteSpace(turnContext.Activity.Text))
            {
                eocActivityMessage += $"\n\nText: {turnContext.Activity.Text}";
            }

            if ((turnContext.Activity as Activity)?.Value != null)
            {
                eocActivityMessage += $"\n\nValue: {JsonConvert.SerializeObject((turnContext.Activity as Activity)?.Value)}";
            }

            await turnContext.SendActivityAsync(MessageFactory.Text(eocActivityMessage), cancellationToken);

            // We are back at the root
            await turnContext.SendActivityAsync(MessageFactory.Text("Back in the root dotnet bot."), cancellationToken);
            await turnContext.SendActivityAsync(MessageFactory.Attachment(GetOptionsAttachment()), cancellationToken);


            // Save conversation state
            await _conversationState.SaveChangesAsync(turnContext, cancellationToken: cancellationToken);
        }

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text("Hello and welcome!"), cancellationToken);
                }
            }
        }
    }
}
